version: '3.2'
services:
  database:
    image: mysql:8.0
    ports:
      - "3309:3306"
    volumes:
      - ./raw:/home/col/raw
      - ./coldp:/home/col/coldp
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ITIS
    command: ['mysqld', '--character-set-server=latin1', '--collation-server=latin1_general_ci', '--default_storage_engine=MYISAM', '--secure-file-priv=', '--default-authentication-plugin=mysql_native_password']
  conversion:
    build:
      context: .
      dockerfile: ./docker/conversion.Dockerfile
    depends_on:
      - database
    volumes:
      - ./raw:/home/col/raw
      - ./scripts:/home/col/scripts
      - ./coldp:/home/col/coldp
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    entrypoint: python /home/col/scripts/convert.py
    tty: true

